42AGV/ft_transcendence

.github/workflows/transcendence-app_check.yml, .github/workflows/webapp_check.yml, .gitignore, transcendence-app/package-lock.json, transcendence-app/package.json, transcendence-app/src/app.service.ts, webapp/.prettierrc, webapp/package-lock.json, webapp/package.json
=> #10 add basic GH actions for checking frontend and backend

README.md, transcendence-app/README.md
closes #3
⚠️ Disclaimer! what you'll see is purely based on my opinion and experience.
The idea is to discuss every point through a review so we all agree how we want to work as a team
=> #3 Add contributing documentation 

transcendence-app/nest-cli.json, transcendence-app/package-lock.json, transcendence-app/package.json, transcendence-app/src/main.ts, transcendence-app/src/oauth42/oauth42.controller.ts
This PR adds the swagger module, which generates OpenAPI documentation automatically.
We can access the documentation at http://localhost:3000/api, and the JSON file at http://localhost:3000/api-json
closes #36
=> #36/research about open api as a way to define our api

transcendence-app/src/auth/auth.controller.ts, transcendence-app/src/shared/enums/boolean-string.enum.ts, transcendence-app/src/user/decorators/user.decorator.ts, transcendence-app/src/user/dto/user.pagination.dto.ts, transcendence-app/src/user/user.controller.ts, transcendence-app/src/user/user.service.ts
This PR updates the API documentation at http://127.0.0.1:3000/api
closes #49
=> Update API documentation

webapp/package-lock.json, webapp/package.json, webapp/src/index.css, webapp/src/index.tsx, webapp/src/pages/Landing/Landing.tsx, webapp/src/pages/Landing/__tests__/Landing.test.tsx, webapp/src/pages/Users/Users.css, webapp/src/pages/Users/Users.tsx, webapp/src/pages/index.ts, webapp/src/shared/components/NavigationItem/NavigationItem.css, webapp/src/shared/components/NavigationItem/NavigationItem.tsx, webapp/src/shared/components/index.ts
closes #57
closes #78
Also, I've installed the React Router package to test if the color of the `NavigationItem` changes when it is active.
Maybe we could also close the task #78?
=> #57 Create navigation item UI component

README.md
=> #87 Add documentation on how to run/deploy the application

package-lock.json, webapp/src/index.css, webapp/src/pages/Landing/Landing.css, webapp/src/pages/Landing/Landing.tsx, webapp/src/shared/components/Avatar/Avatar.css, webapp/src/shared/components/Avatar/Avatar.tsx, webapp/src/shared/components/Icon/Icon.tsx, webapp/src/shared/components/Status/Status.tsx, webapp/src/shared/components/index.ts
=> Avatar UI component

webapp/src/index.css, webapp/src/pages/ComponentsBook/ComponentsBook.css, webapp/src/shared/components/Button/Button.css
- Unify fonts: from `px` to `rem` and also created a [shared team library in Figma](https://www.figma.com/file/0es84Oh1roPphFOd2GYysn/Library?node-id=196%3A309) with all updated fonts
- Added line-height from Figma
- Move button to `rem` so it's responsive
closes #101
=> #101 unify fonts with Figma

transcendence-app/src/shared/local-file/local-file.service.ts, transcendence-app/src/user/user.controller.spec.ts, transcendence-app/src/user/user.controller.ts, transcendence-app/src/user/user.service.ts
GET [/api/v1/users/avatar](http://localhost:3000/api#/users/UserController_getCurrentUserAvatar) -> get the avatar of the currently authenticated user
GET [/api/v1/users/{uuid}/avatar](http://localhost:3000/api#/users/UserController_getAvatar) -> get the avatar of the user with uuid
Subtask of #123
=> #123/Create controllers to fetch the user avatar

transcendence-app/package-lock.json, transcendence-app/package.json, transcendence-app/src/shared/local-file/local-file.service.ts, transcendence-app/src/shared/utils.ts, transcendence-app/src/user/infrastructure/db/postgres/userPostgres.repository.ts, transcendence-app/src/user/infrastructure/db/user.repository.ts, transcendence-app/src/user/user.controller.spec.ts, transcendence-app/src/user/user.controller.ts, transcendence-app/src/user/user.service.ts
PUT [/api/v1/users/avatar](http://localhost:3000/api#/users/UserController_uploadAvatar) -> update the avatar of the currently authenticated user
Subtask of #123
=> #123/Create controller to update the user avatar

webapp/src/index.tsx, webapp/src/pages/UserPage/UserPage.tsx, webapp/src/pages/Users/Users.tsx, webapp/src/shared/components/RowsList/RowsList.tsx
we need a ui to see user pages other than for self
=> user/:id page

webapp/src/pages/UserPage/UserPage.css, webapp/src/pages/UserPage/UserPage.tsx, webapp/src/shared/components/Row/Row.css
user page style was a bit off,
this fixes it
=> #69/adjust user page style

db/setup/queries.sql, webapp/src/index.css, webapp/src/index.tsx, webapp/src/pages/EditUserPage/EditUserPage.css, webapp/src/pages/EditUserPage/EditUserPage.tsx, webapp/src/pages/UserPage/UserPage.tsx, webapp/src/pages/index.ts, webapp/src/shared/components/Button/Button.tsx, webapp/src/shared/components/Input/EditUserForm.css, webapp/src/shared/components/Input/EditUserForm.tsx, webapp/src/shared/urls.ts
Closes #71 
Now works with a confirmation window and an alert. We can change it to a better approach if you want.
=> #71/Create edit user page

webapp/src/shared/components/DispatchPage/DispatchPage.tsx, webapp/src/shared/components/Input/SearchForm.tsx, webapp/src/shared/components/RowsList/RowsList.tsx, webapp/src/shared/hooks/UseSearch.tsx
[Infinite Scrolling With React](https://www.youtube.com/watch?v=NZKUirTtxcg)
[IntersectionObserver](https://www.youtube.com/watch?v=2IbRtjez6ag)
close #146
=> #146/Add pagination to the Users UI page

webapp/src/pages/LandingPage/LandingPage.css
There was some space between the bottom paddle and the ball.
=> Fix landing pong animation

webapp/src/pages/LandingPage/LandingPage.css, webapp/src/pages/LandingPage/LandingPage.tsx, webapp/src/pages/LoginPage/LoginPage.css, webapp/src/pages/LoginPage/LoginPage.tsx
closes #187
Result:
https://user-images.githubusercontent.com/57688116/190526185-411a5a15-8950-4c9e-ad77-6f255ad781fb.mp4
=> #187/fix landing alignment

webapp/src/pages/LoginPage/LoginPage.tsx, webapp/src/pages/RegisterPage/RegisterPage.tsx
Closes #181
After login, redirect the user to the DEFAULT_LOGIN_REDIRECT_URL page when accessing the login an register page
=> #181 Fix navigation to login and register page when logged in

transcendence-app/src/shared/block/block.module.ts, transcendence-app/src/shared/block/block.service.ts, transcendence-app/src/shared/block/infrastructure/block.entity.ts, transcendence-app/src/shared/block/infrastructure/block.repository.ts, transcendence-app/src/shared/block/infrastructure/db/block.postgres.repository.ts, transcendence-app/src/shared/db/db.module.ts, transcendence-app/src/shared/db/models.ts
=> #209/Create-a-database-method-to-create-a-block

transcendence-app/package-lock.json, transcendence-app/package.json, transcendence-app/src/auth/auth.service.ts, transcendence-app/src/auth/oauth42.strategy.ts, transcendence-app/src/shared/local-file/local-file.service.ts, transcendence-app/src/user/user.service.ts, transcendence-app/test/auth/auth.e2e-spec.ts, transcendence-app/types/github-like-avatar-generator.d.ts
=> #176 default avatars on registration

.gitignore, transcendence-app/src/chat/chat.controller.ts, transcendence-app/src/chat/chat.service.ts, transcendence-app/swagger-spec.yaml
=> #228/Create an endpoint to get a chatroom by id

transcendence-app/src/user/dto/user.dto.ts, transcendence-app/src/user/user.service.ts
I've made this comment (https://github.com/42AGV/ft_transcendence/pull/278#discussion_r1008697618) but forgot to push the commit before merging the PR #278 :sweat_smile:
=> #216 - Return an instance and not a plain js object

transcendence-app/src/auth/auth.service.ts, transcendence-app/src/chat/chat.service.ts, transcendence-app/src/shared/password.ts
=> #269/Create a BaseService to extend User and Chat common services

transcendence-app/src/chat/chatroom/infrastructure/db/postgres/chatroom.postgres.repository.ts, transcendence-app/src/shared/db/postgres/postgres.repository.ts, transcendence-app/src/shared/db/postgres/postgresConnection.provider.ts, transcendence-app/src/shared/db/postgres/utils.ts, transcendence-app/src/user/infrastructure/db/postgres/user.postgres.repository.ts
This PR addresses [this suggestion](https://github.com/42AGV/ft_transcendence/pull/304#discussion_r1015126324)
close #309
=> #309/Refactor transactional methods

transcendence-app/src/chat/chat.controller.ts, transcendence-app/src/chat/chat.gateway.ts, webapp/src/pages/ChatPage/ChatPage.tsx, webapp/src/pages/ChatroomPage/ChatroomPage.css, webapp/src/pages/ChatroomPage/ChatroomPage.tsx, webapp/src/pages/ChatroomPage/components/ChatroomMessages/ChatroomMessages.tsx, webapp/src/pages/UsersPage/UsersPage.tsx, webapp/src/shared/constants.ts
=> #226/create a chat room page

transcendence-app/src/chat/chat.controller.ts, transcendence-app/src/chat/chatroom/chatroom-member/chatroom-member.service.ts, transcendence-app/src/chat/chatroom/chatroom-member/infrastructure/db/chatroom-member.repository.ts, transcendence-app/src/chat/chatroom/chatroom-member/infrastructure/db/postgres/chatroom-member.postgres.repository.ts, transcendence-app/src/chat/chatroom/infrastructure/db/chatroom.entity.ts, transcendence-app/src/chat/chatroom/infrastructure/db/chatroom.repository.ts, transcendence-app/src/chat/chatroom/infrastructure/db/postgres/chatroom.postgres.repository.ts
=> #218/Create an endpoint to remove a member from a chatroom

webapp/src/index.tsx, webapp/src/pages/ChatroomPage/ChatroomPage.css, webapp/src/pages/ChatroomPage/ChatroomPage.tsx, webapp/src/pages/ComponentsBookPage/ComponentsExamples/SnackBarExample.tsx, webapp/src/pages/EditAvatarPage/EditAvatarPage.tsx, webapp/src/pages/LoginPage/LoginPage.css, webapp/src/pages/LoginPage/LoginPage.tsx, webapp/src/pages/RegisterPage/RegisterPage.css, webapp/src/pages/RegisterPage/RegisterPage.tsx, webapp/src/shared/components/Input/EditUserForm.tsx, webapp/src/shared/components/Snackbar/Snackbar.css, webapp/src/shared/components/Snackbar/Snackbar.tsx, webapp/src/shared/components/index.ts, webapp/src/shared/context/NotificationContext.tsx, webapp/src/shared/types.ts
closes #319 
Here is the idea:
1) we have a shared notification context to display push message for users
2) we wrap all the routes with the context so notifications are available across the app
3) we only have to use `notify(msg)` and `warn(msg)` to display messages to the user
=> #319 / create a notification context

transcendence-app/src/chat/chat.controller.ts, transcendence-app/src/chat/chat.service.ts
=> #325/Create endpoint and method to delete a chatroom

transcendence-app/src/chat/chat.controller.ts, transcendence-app/src/chat/chat/infrastructure/db/postgres/chat-message.postgres.repository.ts, transcendence-app/src/chat/chatroom/chatroom-member/chatroom-member.service.ts, transcendence-app/src/chat/chatroom/chatroom-member/infrastructure/db/chatroom-member.repository.ts, transcendence-app/src/chat/chatroom/chatroom-member/infrastructure/db/postgres/chatroom-member.postgres.repository.ts
=> #297/add pagination to get chatroommembers for a particular chatroom

transcendence-app/src/chat/chat.controller.ts, transcendence-app/src/chat/chatroom/chatroom-member/chatroom-member.service.ts
=> #339/ DELETE chatroom member endpoint

transcendence-app/src/chat/chat.controller.ts, transcendence-app/src/chat/chat.service.ts, transcendence-app/src/chat/chatroom/infrastructure/db/chatroom.repository.ts, transcendence-app/src/chat/chatroom/infrastructure/db/postgres/chatroom.postgres.repository.ts
=> #264/get chatrooms for the auth user

transcendence-app/src/chat/chat.controller.ts, transcendence-app/src/chat/chat.gateway.ts, transcendence-app/src/chat/chatroom/chatroom-member/chatroom-member.service.ts, webapp/src/pages/AuthUserPage/AuthUserPage.tsx, webapp/src/pages/ChatroomDetailsPage/ChatroomDetailsPage.tsx, webapp/src/pages/ChatroomPage/ChatroomPage.tsx, webapp/src/pages/CreateChatroomPage/CreateChatroomPage.tsx, webapp/src/pages/EditChatroomMemberPage/EditChatroomMemberPage.css, webapp/src/pages/EditChatroomMemberPage/EditChatroomMemberPage.tsx, webapp/src/pages/EditChatroomMemberPage/components/ToggleSwitchSet.tsx, webapp/src/shared/components/Icon/Icon.tsx, webapp/src/shared/components/Icon/assets/icons/index.ts, webapp/src/shared/components/Icon/assets/icons/remove.svg, webapp/src/shared/components/ToggleSwitch/ToggleSwitch.tsx, webapp/src/shared/components/templates/AvatarPageTemplate/AvatarPageTemplate.tsx, webapp/src/shared/context/NotificationContext.tsx
We need a page to edit chat member options
=> #207/create edit chatroom member page

db/setup/schema.sql, transcendence-app/src/chat/chat.module.ts, transcendence-app/src/chat/chat.service.ts, transcendence-app/src/chat/chatroom/dto/chatroom.dto.ts, transcendence-app/src/chat/chatroom/infrastructure/db/chatroom.entity.ts, transcendence-app/src/chat/chatroom/infrastructure/db/chatroom.repository.ts, transcendence-app/src/chat/chatroom/infrastructure/db/postgres/chatroom.postgres.repository.ts, transcendence-app/src/shared/avatar/avatar.controller.ts, transcendence-app/src/shared/avatar/avatar.module.ts, transcendence-app/src/shared/avatar/avatar.service.ts, transcendence-app/src/user/user.controller.ts, transcendence-app/src/user/user.module.ts, transcendence-app/src/user/user.service.ts, webapp/src/pages/ChatPage/ChatPage.tsx, webapp/src/pages/CreateChatroomPage/CreateChatroomPage.tsx, webapp/src/pages/EditChatroomDetailsPage/EditChatroomDetailsPage.tsx, webapp/src/pages/EditChatroomMemberPage/EditChatroomMemberPage.tsx, webapp/src/pages/JoinChatroomPage/JoinChatroomPage.tsx, webapp/src/shared/components/templates/AvatarPageTemplate/AvatarPageTemplate.tsx, webapp/src/shared/urls.ts
=> #317/Add generated avatar to new chatrooms

webapp/src/index.tsx, webapp/src/pages/ChatPage/DiscoverChatPage.tsx, webapp/src/pages/ChatPage/template/ChatPageTemplate.tsx, webapp/src/pages/EditChatroomMemberPage/EditChatroomMemberPage.tsx, webapp/src/pages/index.ts
=> #353/created discover chatroom page

.github/workflows/deploy_do.yml, Makefile
=> #365/add a GitHub action to deploy to digital ocean when we merge to the main branch

.github/workflows/deploy_do.yml
Third time's the charm
Fix #365
=> #365/Fix deploy action

.github/workflows/deploy_do.yml
Remove `$default-branch` variable and use `main`
:crossed_fingers:
=> #365/Fix deploy action branch

.github/workflows/production-run_check.yml, .github/workflows/transcendence-app_check.yml, .github/workflows/webapp_check.yml
Remove the on push to `$default-branch` event
close #371
=> #371/Update actions workflows

transcendence-app/src/chat/chat.gateway.ts, transcendence-app/src/chat/chat.module.ts, transcendence-app/src/chat/chat.service.ts, transcendence-app/src/chat/chat/dto/create-chat-message.dto.ts, transcendence-app/src/chat/chat/infrastructure/db/chat-message.repository.ts, transcendence-app/src/user/user.service.ts
=> #286 create ws event to enable one-to-one messages

webapp/src/pages/ChatPage/ChatPage.tsx, webapp/src/pages/ChatroomPage/ChatroomPage.tsx, webapp/src/shared/components/templates/ChatMessagingTemplate/ChatMessagingTemplate.tsx, webapp/src/shared/context/UserBlocklistContext.tsx
I think this bug was happening because of some `useEffect`/`useCallback` dependencies.
close #401
=> #401/Fix the empty chatrooms bug

transcendence-app/src/auth/local.guard.ts, transcendence-app/src/auth/oauth42.guard.ts
=> #415/forbid login for banned users

transcendence-app/src/auth/local.guard.ts, transcendence-app/src/auth/oauth42.guard.ts, webapp/src/shared/components/NavigationBar/NavigationBar.tsx, webapp/src/shared/urls.ts
I broke the previous [PR](https://github.com/42AGV/ft_transcendence/pull/412), so I'm opening this one again, with exactly the same content it had
=> #411/add admin item for admin users to navbar

transcendence-app/src/auth/auth.controller.ts, transcendence-app/src/auth/local.guard.ts, transcendence-app/src/auth/oauth42.guard.ts, transcendence-app/src/authorization/authorization.service.ts, transcendence-app/src/authorization/casl-ability.factory.ts, transcendence-app/src/authorization/decorators/configure-param.decorator.ts, transcendence-app/src/authorization/dto/user-with-authorization.response.dto.ts, transcendence-app/src/authorization/guards/crm-policies.guard.ts, transcendence-app/src/authorization/guards/global-policies.guard.ts, transcendence-app/src/chat/chat.controller.ts, webapp/src/shared/components/NavigationBar/NavigationBar.tsx, webapp/src/shared/urls.ts
=> #409/get user with roles endpoint

transcendence-app/src/auth/oauth42.strategy.ts, transcendence-app/src/shared/constants.ts, transcendence-app/src/user/user.service.ts
as described in #419
Closes #419
=> #419/fix bug when username of a 42 user already exists

transcendence-app/src/auth/local.guard.ts, transcendence-app/src/auth/oauth42.guard.ts, transcendence-app/src/authorization/authorization.service.ts, transcendence-app/src/authorization/casl-ability.factory.ts, transcendence-app/src/authorization/dto/user-with-authorization.response.dto.ts, transcendence-app/src/authorization/infrastructure/db/chatroom-member-with-authorization.entity.ts, transcendence-app/src/authorization/infrastructure/db/postgres/user-to-role.postgres.repository.ts, transcendence-app/src/authorization/infrastructure/db/user-with-authorization.entity.ts
=> #420/rename g_xxx roles

transcendence-app/src/authorization/authorization.service.ts, transcendence-app/src/authorization/guards/crm-policies.guard.ts, transcendence-app/src/chat/chat.gateway.ts, transcendence-app/src/shared/avatar/avatar.module.ts, transcendence-app/src/shared/guards/authenticated.guard.ts, transcendence-app/src/user/user.controller.spec.ts, transcendence-app/src/user/user.module.ts, transcendence-app/test/auth/auth.e2e-spec.ts, transcendence-app/test/user/user.e2e-spec.ts
=> #415/banned users shouldn't be able to use any endpoint

transcendence-app/src/auth/local.guard.ts, transcendence-app/src/auth/oauth42.guard.ts, transcendence-app/src/authorization/casl-ability.factory.ts, transcendence-app/src/socket/socket.service.ts
=> #434/fix owner login to be admitted even if banned

transcendence-app/src/auth/auth.controller.ts
Add `await` to the call to `AuthService.isTwoFactorAuthenticationCodeValid` method
Thanks @fizcamposancos for finding this :rocket:
close #440
=> Fix the validate 2FA endpoint

transcendence-app/src/auth/auth.controller.ts, transcendence-app/src/auth/auth.service.ts, transcendence-app/src/auth/session.serializer.ts, transcendence-app/src/chat/chat.gateway.ts, webapp/src/index.tsx, webapp/src/pages/AuthUserPage/AuthUserPage.tsx, webapp/src/pages/EnableTwoFactorAuthPage/EnableTwoFactorAuthPage.css, webapp/src/pages/EnableTwoFactorAuthPage/EnableTwoFactorAuthPage.tsx, webapp/src/pages/LoginPage/LoginPage.tsx, webapp/src/pages/ValidateTwoFactorAuthPage/ValidateTwoFactorAuthPage.css, webapp/src/pages/ValidateTwoFactorAuthPage/ValidateTwoFactorAuthPage.tsx, webapp/src/pages/index.ts, webapp/src/shared/urls.ts
=> #439/Implement 2FA with TOTP frontend

transcendence-app/Dockerfile
closes #449
Good catch @Damrod, thank you!!
=> #449 / fix prod deployment issues

transcendence-app/seeds/001_seed_users.ts, transcendence-app/seeds/002_seed_chatrooms.ts
As explained in #458
closes #458
=> #458/Downsize seeds

webapp/src/pages/ComponentsBookPage/ComponentsBookPage.tsx, webapp/src/pages/ComponentsBookPage/ComponentsExamples/GameSpinnerExample.tsx, webapp/src/shared/components/GameSpinner/GameSpinner.css, webapp/src/shared/components/GameSpinner/GameSpinner.tsx, webapp/src/shared/components/index.ts
As described in #456
closes #456
=> #456/spinner for game queue

webapp/src/pages/ComponentsBookPage/ComponentsBookPage.tsx, webapp/src/pages/ComponentsBookPage/ComponentsExamples/TimerExample.tsx, webapp/src/shared/components/Timer/Timer.css, webapp/src/shared/components/Timer/Timer.tsx, webapp/src/shared/components/index.ts
as detailed in #453 
closes #453
=> #453/timer component

packages/pong-engine/src/queue.dto.ts, transcendence-app/src/game/game.queue.gateway.ts, transcendence-app/src/game/game.queue.service.ts, transcendence-app/src/game/infrastructure/db/challenges-pending.repository.ts, transcendence-app/src/game/infrastructure/db/games-ongoing.repository.ts, transcendence-app/src/game/infrastructure/db/memoryModels/gameset-abstract.model.ts, webapp/src/pages/GameQueuePage/GameQueuePage.tsx, webapp/src/pages/PlayPage/PlayPage.tsx, webapp/src/pages/UserPage/UserPage.tsx, webapp/src/shared/context/GamePairingContext.tsx, webapp/src/shared/context/UserBlocklistContext.tsx
As described in #479, + some bugfix from create GamePairing Ws events PR
=> #479/sync game queue status across tabs

transcendence-app/src/game/game.queue.gateway.ts
=> #479/Challenges should also emit game ready 

webapp/src/pages/LoginPage/LoginPage.css, webapp/src/pages/LoginPage/LoginPage.tsx, webapp/src/pages/RegisterPage/RegisterPage.css, webapp/src/pages/RegisterPage/RegisterPage.tsx, webapp/src/shared/components/index.ts, webapp/src/shared/components/templates/LandingAnimationPageTemplate/LandingAnimationPageTemplate.css, webapp/src/shared/components/templates/LandingAnimationPageTemplate/LandingAnimationPageTemplate.tsx
=> #375/align login and register page

webapp/src/pages/ChatPage/ChatPage.tsx, webapp/src/pages/ChatroomPage/ChatroomPage.tsx, webapp/src/pages/UserPage/UserPage.tsx, webapp/src/shared/components/Game/hooks/useOnlineGame.tsx, webapp/src/shared/context/GamePairingContext.tsx, webapp/src/shared/context/NotificationContext.tsx
As explained in the ticket #489
=> #489/webapp websocket exception handler now only in one place

webapp/src/pages/RegisterPage/RegisterPage.css
Hopefully this will now fix any further mismatch
=> #375/fixed register style

transcendence-app/src/game/game.queue.gateway.ts, webapp/src/pages/PlayPage/PlayPage.tsx, webapp/src/shared/components/Button/Button.css, webapp/src/shared/components/Button/CollapsibleButton.css, webapp/src/shared/components/Button/CollapsibleButton.tsx, webapp/src/shared/components/index.ts, webapp/src/shared/context/GamePairingContext.tsx
=> #503/persist queued/playing UI status and action

transcendence-app/src/game/game.service.ts, webapp/src/shared/components/Game/hooks/useOnlineGame.tsx
=> #495/Finish the game when a player reaches an arbitrary number of points

transcendence-app/src/game/game.gateway.ts, transcendence-app/src/game/game.service.ts, webapp/src/pages/PlayPage/PlayPage.css, webapp/src/pages/PlayPage/PlayPage.tsx
=> #488/List ongoing games and update them in real-time

packages/transcendence-shared/src/game/types.ts, packages/transcendence-shared/src/index.ts, transcendence-app/src/game/game.gateway.ts, transcendence-app/src/game/game.service.ts, webapp/src/shared/context/UserStatusContext.tsx
=> #487/Add 'playing' status variant to user status

transcendence-app/src/game/infrastructure/db/postgres/game.postgres.repository.ts
=> #515/Fix the ORDER BY clause of getPaginatedUserGames

transcendence-app/src/game/game.service.ts, transcendence-app/src/socket/socket.gateway.ts, webapp/src/shared/context/GamePairingContext.tsx
To test this, you can do either of these while playing a game:
- Logout then login again.
- Close all the app tabs, then open a new app tab.
close #494
=> #494/Handle user login after disconnecting from a game

packages/pong-engine/src/game.ts, packages/pong-engine/src/index.ts, packages/pong-engine/src/models.ts, packages/pong-engine/src/state.ts, transcendence-app/src/game/dto/game-input.dto.ts, transcendence-app/src/game/game.service.ts, webapp/src/shared/components/Game/hooks/useGameControls.tsx, webapp/src/shared/components/Game/hooks/useOnlineGame.tsx
=> #496/Enable paddle drag in online games

transcendence-app/src/game/game.service.ts, webapp/src/shared/components/Game/hooks/useOnlineGame.tsx
=> #497/Show a notification when a player disconnects or pauses the game

transcendence-app/src/game/game.service.ts
=> #523/If a player quits a game, they lose it

transcendence-app/src/authorization/authorization.service.ts, transcendence-app/src/authorization/dto/user-with-authorization.response.dto.ts, transcendence-app/src/shared/dtos/user-with-level.dto.ts, transcendence-app/src/user/dto/user.response.dto.ts, transcendence-app/src/user/user.controller.spec.ts, transcendence-app/src/user/user.controller.ts, transcendence-app/src/user/user.service.ts, webapp/src/pages/AuthUserPage/AuthUserPage.tsx, webapp/src/pages/EditChatroomMemberPage/EditChatroomMemberPage.tsx, webapp/src/pages/EditUserAvatarPage/EditUserAvatarPage.tsx, webapp/src/pages/LoginPage/LoginPage.tsx, webapp/src/pages/UserPage/UserPage.tsx, webapp/src/pages/UserStatsPage/UserStatsPage.tsx, webapp/src/pages/UsersPage/FriendsPage.tsx, webapp/src/pages/UsersPage/UsersPage.tsx, webapp/src/pages/ValidateTwoFactorAuthPage/ValidateTwoFactorAuthPage.tsx
=> #533/retrieve levels for users

transcendence-app/src/authorization/authorization.service.ts, transcendence-app/src/authorization/dto/user-with-authorization.response.dto.ts, transcendence-app/src/game/game.controller.ts, transcendence-app/src/game/stats/dto/game-stats-query.dto.ts, transcendence-app/src/game/stats/dto/game-stats.dto.ts, transcendence-app/src/game/stats/game-stats.service.ts, transcendence-app/src/game/stats/infrastructure/db/postgres/user-level.postgres.repository.ts, transcendence-app/src/game/stats/infrastructure/db/user-level.repository.ts, transcendence-app/src/shared/dtos/user-with-level.dto.ts, transcendence-app/src/user/dto/user.response.dto.ts, transcendence-app/src/user/user.controller.spec.ts, transcendence-app/src/user/user.controller.ts, transcendence-app/src/user/user.service.ts, webapp/src/pages/AuthUserPage/AuthUserPage.tsx, webapp/src/pages/EditChatroomMemberPage/EditChatroomMemberPage.tsx, webapp/src/pages/EditUserAvatarPage/EditUserAvatarPage.tsx, webapp/src/pages/LoginPage/LoginPage.tsx, webapp/src/pages/UserPage/UserPage.tsx, webapp/src/pages/UserStatsPage/UserStatsPage.tsx, webapp/src/pages/UsersPage/FriendsPage.tsx, webapp/src/pages/UsersPage/UsersPage.tsx, webapp/src/pages/ValidateTwoFactorAuthPage/ValidateTwoFactorAuthPage.tsx
As explained in #531
closes #531
updates #507
=> #531/backend stats implementation

transcendence-app/src/game/game.controller.ts, transcendence-app/src/game/infrastructure/db/postgres/game.postgres.repository.ts, transcendence-app/src/game/stats/dto/game-stats.dto.ts, transcendence-app/src/game/stats/dto/pagination-query-with-game-mode.dto.ts, transcendence-app/src/game/stats/game-stats.service.ts, transcendence-app/src/game/stats/infrastructure/db/postgres/user-level.postgres.repository.ts, transcendence-app/src/game/stats/infrastructure/db/user-level-with-timestamp.entity.ts, transcendence-app/src/game/stats/infrastructure/db/user-level.repository.ts, webapp/src/pages/UserMatchHistoryPage/UserMatchHistoryPage.tsx, webapp/src/pages/UserPage/UserPage.tsx, webapp/src/pages/UserStatsPage/UserStatsPage.css, webapp/src/pages/UserStatsPage/UserStatsPage.tsx
=> #553/fix buttons and remove pagination from get levels endpoints

transcendence-app/src/game/game.service.ts, webapp/src/shared/components/Game/Game.css, webapp/src/shared/components/Game/Game.tsx, webapp/src/shared/components/Game/hooks/useOnlineGame.tsx, webapp/src/shared/components/Score/Score.css
=> #551/Use score component in Game component

transcendence-app/src/auth/local.guard.ts, transcendence-app/src/auth/oauth42.guard.ts, transcendence-app/src/authorization/authorization.service.ts, transcendence-app/src/authorization/guards/base-policies.guard.ts, transcendence-app/src/authorization/guards/crm-policies.guard.ts, transcendence-app/src/authorization/guards/global-policies.guard.ts, transcendence-app/src/chat/chatroom/chatroom-member/decorators/auth-chatroom-member.decorator.ts, transcendence-app/src/chat/chatroom/chatroom-member/decorators/dest-chatroom-member.decorator.ts, transcendence-app/src/shared/guards/authenticated.guard.ts, transcendence-app/src/socket/socket.service.ts, transcendence-app/src/user/decorators/user.decorator.ts, webapp/src/pages/ChatroomPage/ChatroomPage.tsx, webapp/src/pages/GameRulesPage/GameRulesPage.css, webapp/src/pages/PlayPage/PlayPage.css, webapp/src/pages/UserPage/UserPage.css, webapp/src/shared/components/templates/AvatarPageTemplate/AvatarPageTemplate.css, webapp/src/shared/components/templates/MainTabPageTemplate/MainTabPageTemplate.css
As explained in #549
UPDATE:
This PR fixes the internal server errors, and also fixes some style issues we had across the whole website, where buttons that should be in matching places were not.
=> #549/ fix internal server error ws exception

webapp/src/shared/components/Game/hooks/useOnlineGame.tsx
I pushed but forgot to save the file, so I missed this change suggested by @gbudau in last PR 😅
=> fix lag time reference assignation

transcendence-app/src/game/game.service.ts
This PR adds a few helper methods to the game service to update the game info only if the game exists. This prevents recreating a game after being deleted because of concurrent access.
close #562
=> #562/White screen in play page

transcendence-app/src/game/game.gateway.ts, transcendence-app/src/game/game.service.ts, webapp/src/shared/components/Game/Game.tsx, webapp/src/shared/components/Game/hooks/useOnlineGame.tsx
=> #564/Sometimes the game configuration option is skipped

webapp/src/shared/components/Game/hooks/useOnlineGame.tsx
=> #571/Add time between slow connection warnings

transcendence-app/src/game/stats/game-stats.service.ts, transcendence-app/src/game/stats/infrastructure/db/postgres/user-level.postgres.repository.ts, transcendence-app/src/game/stats/infrastructure/db/user-level.repository.ts, webapp/src/pages/AuthUserPage/AuthUserPage.tsx, webapp/src/pages/UserStatsPage/UserStatsPage.tsx
=> #577/add additional gamemodes to stats

webapp/src/shared/components/Row/ScoreRow.css, webapp/src/shared/components/Row/ScoreRow.tsx
=> #582/Fix ScoreRow list appearance

transcendence-app/src/game/game.gateway.ts, transcendence-app/src/game/game.service.ts, webapp/src/pages/UserPage/UserPage.tsx
=> #586/If a user is playing add a way to navigate to their active game from their user page

webapp/src/shared/components/Game/Game.css, webapp/src/shared/components/Game/Game.tsx, webapp/src/shared/components/Score/Score.tsx
closes #551 
closes #510 
I tried several designs, large avatars, on both sides, vertical, horizontal,... And this is which I like the most. Please have a look at it, and if you have any other idea it will be welcome.
Or we can leave it like the mobile design if this doesn't convince you
=> #510-551/Score for desktop design

transcendence-app/src/user/infrastructure/db/friend.repository.ts, transcendence-app/src/user/infrastructure/db/postgres/friend.postgres.repository.ts, transcendence-app/src/user/infrastructure/db/postgres/user.postgres.repository.ts, transcendence-app/src/user/infrastructure/db/user.entity.ts, transcendence-app/src/user/infrastructure/db/user.repository.ts, transcendence-app/src/user/user.controller.ts, transcendence-app/src/user/user.service.ts
as explained in #585
closes #585
=> #585/get users with levels in single query

webapp/src/shared/components/Row/ScoreRow.css
=> #590/Fix score overflow in ScoreRow component

Makefile, docker-compose.override.yml, docker-compose.prod.yml, docker-compose.yml
=> #592/Run migrations from docker compose file

docker-compose.yml
=> #594/fix db health check trying to connect to non existing database

transcendence-app/seeds/utils/index.ts, transcendence-app/src/auth/auth.controller.ts, transcendence-app/src/auth/auth.service.ts, transcendence-app/src/chat/chat.controller.ts, transcendence-app/src/chat/chat.service.ts, transcendence-app/src/shared/local-file/local-file.service.ts, transcendence-app/swagger-spec/swagger-spec.yaml, webapp/src/shared/generated/.openapi-generator/FILES
=> #457/investigate sporadic add owner migration failure fix
